# Configuración Principal
owner: EmilianoBechard
repo: status-page

# Sitios a monitorear
sites:
  - name: "Bechard Studio Web"
    url: https://bechard-studio.com
  - name: "n8n Automation"
    url: https://n8n.bechard-studios.com
  - name: "G52 Monitor"
    url: https://monitor.bechard-studio.com
  - name: "Worklo"
    url: https://esta-pagina-no-existe-12345.com

# Configuración de la Web (Una sola vez)
status-website:
  cname: status.bechard-studio.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bechard Studio Status
  introTitle: "**Bechard Studio** Status"
  introMessage: "Bienvenido al monitor de servicios de Bechard Studio. Monitoreado desde la nube sin usar recursos del G52."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/EmilianoBechard/status-page

# Usuarios asignados
assignees:
  - EmilianoBechard
notifications:
  - type: ntfy
    topic: monitor_notifications
